

language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

# Comando para rodar os testes
script:
  - py.test testes.py

after script:
  notifications:
    recipients:
      - bruno.novo@concrete.com.br

